<a href="https://colab.research.google.com/github/jongheonleee/LangMaster-AI/blob/main/AI%EC%88%98%EC%97%855%EC%9D%BC%EC%B0%A8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

arr = np.array([i for i in range(10)])
idx = np.array([i % 2 == 0 for i in range(10)])

arr[idx]

array([0, 2, 4, 6, 8])

In [2]:
print(arr % 2)

[0 1 0 1 0 1 0 1 0 1]


In [3]:
print(arr % 2 == 0)

[ True False  True False  True False  True False  True False]


In [4]:
arr[arr % 2 == 0]

array([0, 2, 4, 6, 8])

In [5]:
arr2 = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])
idx = np.array([i*2 for i in range(5)])
arr2[idx]

array([11, 33, 55, 77, 99])

In [6]:
x = np.array([1, 2, 3])
x.dtype

dtype('int64')

In [7]:
x = np.array([1.0, 2.0, 3.0])
x.dtype

dtype('float64')

In [8]:
x = np.array([1, 2, 3.0])
x.dtype

dtype('float64')

In [9]:
print(x[0], x[1], x[2])

1.0 2.0 3.0


In [10]:
x = np.array([1, 2, 3], dtype='f')
x.dtype

dtype('float32')

In [11]:
x[0] + x[1]

np.float32(3.0)

In [12]:
x = np.array([1, 2, 3], dtype='U')
x.dtype

dtype('<U1')

In [13]:
x[0] + x[1]

'12'

In [14]:
a = np.array([1.0, 2.0, -3.0, 0.0])
b = np.array([0.0, 1.0, 0.0, 0.0])
c = a/b

print(c)

[ inf   2. -inf  nan]


<ipython-input-14-e938afc4c3c7>:3: RuntimeWarning: divide by zero encountered in divide
  c = a/b
<ipython-input-14-e938afc4c3c7>:3: RuntimeWarning: invalid value encountered in divide
  c = a/b


In [15]:
a = np.zeros(5)
a.dtype

dtype('float64')

In [16]:
a

array([0., 0., 0., 0., 0.])

In [17]:
b = np.zeros((2, 3))
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
c = np.zeros((5, 2), dtype='i')
c

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int32)

In [19]:
e = np.ones((2, 3, 4), dtype='i8')
e

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [20]:
f = np.ones_like(b, dtype='f')
f

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [21]:
g = np.empty((4, 3))
g

array([[4.28071306e-316, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [24]:
np.arange(10, 5, -1)

array([10,  9,  8,  7,  6])

In [ ]:
# reshape() 부분도 있음